# Generated by Django 2.2 on 2019-04-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Portrait', models.CharField(max_length=500)),
                ('Avatar', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Gear_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.CharField(max_length=255)),
                ('Bracelets', models.CharField(max_length=255)),
                ('Earrings', models.CharField(max_length=255)),
                ('Feet', models.CharField(max_length=255)),
                ('Hands', models.CharField(max_length=255)),
                ('Head', models.CharField(max_length=255)),
                ('Legs', models.CharField(max_length=255)),
                ('MainHand', models.CharField(max_length=255)),
                ('Necklace', models.CharField(max_length=255)),
                ('Ring1', models.CharField(max_length=255)),
                ('Ring2', models.CharField(max_length=255)),
                ('SoulCrystal', models.CharField(max_length=255)),
                ('Waist', models.CharField(max_length=255)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_details', to='Final_Fantasy_App.Character')),
            ],
        ),
        migrations.CreateModel(
            name='WantedGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.CharField(max_length=255)),
                ('Bracelets', models.CharField(max_length=255)),
                ('Earrings', models.CharField(max_length=255)),
                ('Feet', models.CharField(max_length=255)),
                ('Hands', models.CharField(max_length=255)),
                ('Head', models.CharField(max_length=255)),
                ('Legs', models.CharField(max_length=255)),
                ('MainHand', models.CharField(max_length=255)),
                ('Necklace', models.CharField(max_length=255)),
                ('Ring1', models.CharField(max_length=255)),
                ('Ring2', models.CharField(max_length=255)),
                ('SoulCrystal', models.CharField(max_length=255)),
                ('Waist', models.CharField(max_length=255)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_gear', to='Final_Fantasy_App.Character')),
            ],
        ),
        migrations.CreateModel(
            name='GearPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creator', models.CharField(max_length=255)),
                ('Dye', models.CharField(max_length=255)),
                ('Materia', models.CharField(max_length=255)),
                ('Mirage', models.CharField(max_length=255)),
                ('Gear', models.ManyToManyField(to='Final_Fantasy_App.Gear_Details')),
            ],
        ),
    ]
