# Generated by Django 2.2 on 2019-04-17 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Portrait', models.CharField(max_length=500)),
                ('Avatar', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WantedGear',
            fields=[
                ('Icon', models.CharField(default='http://i.imgur.com/SwBRFdO.png', max_length=255)),
                ('Dye', models.CharField(max_length=255)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Materia', models.CharField(max_length=255)),
                ('Mirage', models.CharField(max_length=255)),
                ('gearType', models.CharField(choices=[('body', 'Body'), ('bracelets', 'Bracelets')], max_length=255)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wantedgear', to='Final_Fantasy_App.Character')),
            ],
        ),
        migrations.CreateModel(
            name='GearPiece',
            fields=[
                ('Creator', models.CharField(max_length=255)),
                ('Icon', models.CharField(default='http://i.imgur.com/SwBRFdO.png', max_length=255)),
                ('Dye', models.CharField(max_length=255)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Materia', models.CharField(max_length=255)),
                ('Mirage', models.CharField(max_length=255)),
                ('gearType', models.CharField(choices=[('body', 'Body'), ('bracelets', 'Bracelets')], max_length=255)),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GearPieces', to='Final_Fantasy_App.Character')),
            ],
        ),
    ]
