# Generated by Django 2.2 on 2019-04-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Fantasy_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearpiece',
            name='Name',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='gearpiece',
            name='gearType',
            field=models.CharField(choices=[('body', 'Body'), ('bracelets', 'Bracelets'), ('earrings', 'Earrings'), ('feet', 'Feet'), ('hands', 'Hands'), ('legs', 'Legs'), ('mainhand', 'Main Hand'), ('necklace', 'Necklace'), ('ring1', 'Ring 1'), ('ring2', 'Ring 2'), ('waist', 'Waist')], max_length=255),
        ),
    ]
