# Generated by Django 2.2 on 2019-04-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Fantasy_App', '0002_wantedgear_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedgear',
            name='Name',
            field=models.CharField(default='nameCaster', max_length=255),
        ),
    ]
