# Generated by Django 2.2 on 2019-04-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Fantasy_App', '0002_auto_20190418_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='characterId',
            field=models.CharField(default='3', max_length=500),
        ),
    ]
