# Generated by Django 2.2 on 2019-04-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Fantasy_App', '0003_auto_20190417_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearpiece',
            name='Icon',
            field=models.CharField(default='http://i.imgur.com/SwBRFdO.png', max_length=255),
        ),
    ]
