# Generated by Django 2.2 on 2019-04-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Fantasy_App', '0003_character_characterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearpiece',
            name='Materia',
        ),
    ]
