# Generated by Django 2.2 on 2019-04-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Fantasy_App', '0004_remove_gearpiece_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantedgear',
            name='Materia',
        ),
    ]
