# Generated by Django 2.2 on 2019-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Fantasy_App', '0006_auto_20190421_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearpiece',
            name='gearType',
            field=models.CharField(choices=[('Body', 'Body'), ('Bracelets', 'Bracelets'), ('Earrings', 'Earrings'), ('Feet', 'Feet'), ('Hands', 'Hands'), ('Legs', 'Legs'), ('Mainhand', 'Main Hand'), ('Necklace', 'Necklace'), ('Ring1', 'Ring 1'), ('Ring2', 'Ring 2'), ('Waist', 'Waist')], max_length=255),
        ),
    ]
