# Generated by Django 2.2 on 2019-04-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Fantasy_App', '0008_auto_20190421_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearpiece',
            name='Creator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gearpiece',
            name='Dye',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gearpiece',
            name='Mirage',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
