# Generated by Django 2.2 on 2019-04-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_Fantasy_App', '0012_auto_20190421_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearpiece',
            name='gearType',
            field=models.CharField(choices=[('Body', 'Body'), ('Bracelets', 'Bracelets'), ('Earrings', 'Earrings'), ('Head', 'Head'), ('Feet', 'Feet'), ('Hands', 'Hands'), ('Legs', 'Legs'), ('MainHand', 'Main Hand'), ('OffHand', 'Off Hand'), ('Necklace', 'Necklace'), ('Ring1', 'Ring 1'), ('Ring2', 'Ring 2'), ('SoulCrystal', 'Soul Crystal'), ('Waist', 'Waist')], max_length=255),
        ),
        migrations.AlterField(
            model_name='wantedgear',
            name='gearType',
            field=models.CharField(choices=[('Body', 'Body'), ('Bracelets', 'Bracelets'), ('Earrings', 'Earrings'), ('Head', 'Head'), ('Feet', 'Feet'), ('Hands', 'Hands'), ('Legs', 'Legs'), ('MainHand', 'Main Hand'), ('OffHand', 'Off Hand'), ('Necklace', 'Necklace'), ('Ring1', 'Ring 1'), ('Ring2', 'Ring 2'), ('SoulCrystal', 'Soul Crystal'), ('Waist', 'Waist')], max_length=255),
        ),
    ]
